/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/room-comp-v2.glb 
*/

/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
import React, { useRef, useEffect, useState } from "react";
import { useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { gsap } from "gsap";

export function Room(props) {
  const { nodes, materials } = useGLTF("./models/room-comp-v3.glb");
  const { gl, scene, camera } = useThree();
  const map = useRef(null);
  const [animate, setAnimate] = useState(false);
  const mouseX = useRef(0);
  const mouseY = useRef(0);

  useEffect(() => {
    const onMouseMove = (event) => {
      mouseX.current = (event.clientX / window.innerWidth) * 2 - 1;
      mouseY.current = (event.clientY / window.innerHeight) * 2 - 1;
      setAnimate(true);
    };

    const update = () => {
      if (animate) {
        const coeffX = 0.5;
        const coeffY = 1.5;

        const coeffRotateX = 0.05;
        const coeffRotateY = 0.1;
        const coeffRotateZ = -0.05;

        gsap.to(map.current.position, {
          duration: 5,
          x: -mouseX.current * coeffX + 2,
          y: mouseY.current * coeffY - 8,
          ease: "power3.out",
        });

        gsap.to(map.current.rotation, {
          duration: 5,
          x: -mouseY.current * coeffRotateX + 0.1,
          y: -mouseX.current * coeffRotateY + 3.8,
          z: -mouseX.current * coeffRotateZ,

          ease: "power3.out",
        });
        setAnimate(false);
      }

      gl.render(scene, camera);
      requestAnimationFrame(update);
    };

    window.addEventListener("mousemove", onMouseMove, false);
    update();

    return () => {
      window.removeEventListener("mousemove", onMouseMove, false);
    };
  }, [animate, camera, gl, scene]);
  return (
    <group {...props} dispose={null} ref={map}>
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials["Material.001"]}
        position={[-14.503, 7.77, 20.772]}
        scale={[3.935, 0.078, 5.155]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={materials.projector}
        position={[-16.001, 7.563, 22.797]}
        scale={[0.017, 0.152, 0.017]}
      />
      <group position={[-8.966, 4.602, 21.849]} scale={[1.58, 0.084, 1.616]}>
        <mesh geometry={nodes.Cube012_1.geometry} material={materials.Murs} />
        <mesh
          geometry={nodes.Cube012_2.geometry}
          material={materials["Material.002"]}
        />
        <mesh geometry={nodes.Cube012_3.geometry} material={materials.Sol} />
        <mesh
          geometry={nodes.Cube012_4.geometry}
          material={materials["Mur Vegetal"]}
        />
        <mesh
          geometry={nodes.Cube012_5.geometry}
          material={materials["lambert3.001"]}
        />
        <mesh
          geometry={nodes.Cube012_6.geometry}
          material={materials["lambert3.002"]}
        />
        <mesh
          geometry={nodes.Cube012_7.geometry}
          material={materials["lambert3.003"]}
        />
        <mesh
          geometry={nodes.Cube012_8.geometry}
          material={materials["lambert3.004"]}
        />
        <mesh
          geometry={nodes.Cube012_9.geometry}
          material={materials["lambert3.005"]}
        />
        <mesh
          geometry={nodes.Cube012_10.geometry}
          material={materials["lambert3.006"]}
        />
        <mesh
          geometry={nodes.Cube012_11.geometry}
          material={materials["lambert3.007"]}
        />
        <mesh
          geometry={nodes.Cube012_12.geometry}
          material={materials["lambert3.008"]}
        />
        <mesh
          geometry={nodes.Cube012_13.geometry}
          material={materials["lambert3.009"]}
        />
        <mesh
          geometry={nodes.Cube012_14.geometry}
          material={materials["lambert3.010"]}
        />
        <mesh
          geometry={nodes.Cube012_15.geometry}
          material={materials["lambert3.011"]}
        />
        <mesh
          geometry={nodes.Cube012_16.geometry}
          material={materials["lambert3.012"]}
        />
        <mesh
          geometry={nodes.Cube012_17.geometry}
          material={materials["lambert3.013"]}
        />
        <mesh
          geometry={nodes.Cube012_18.geometry}
          material={materials["lambert3.014"]}
        />
        <mesh
          geometry={nodes.Cube012_19.geometry}
          material={materials["lambert3.015"]}
        />
        <mesh
          geometry={nodes.Cube012_20.geometry}
          material={materials["material_0.001"]}
        />
        <mesh
          geometry={nodes.Cube012_21.geometry}
          material={materials["material_0.002"]}
        />
        <mesh
          geometry={nodes.Cube012_22.geometry}
          material={materials["material_0.003"]}
        />
        <mesh
          geometry={nodes.Cube012_23.geometry}
          material={materials["material_0.006"]}
        />
        <mesh
          geometry={nodes.Cube012_24.geometry}
          material={materials["material_0.007"]}
        />
        <mesh
          geometry={nodes.Cube012_25.geometry}
          material={materials["material_0.009"]}
        />
        <mesh
          geometry={nodes.Cube012_26.geometry}
          material={materials["material_0.010"]}
        />
        <mesh
          geometry={nodes.Cube012_27.geometry}
          material={materials["material_0.013"]}
        />
        <mesh
          geometry={nodes.Cube012_28.geometry}
          material={materials["material_0.014"]}
        />
        <mesh
          geometry={nodes.Cube012_29.geometry}
          material={materials["material_0.015"]}
        />
        <mesh
          geometry={nodes.Cube012_30.geometry}
          material={materials["material_0.016"]}
        />
        <mesh
          geometry={nodes.Cube012_31.geometry}
          material={materials["material_0.017"]}
        />
        <mesh
          geometry={nodes.Cube012_32.geometry}
          material={materials["material_0.018"]}
        />
        <mesh
          geometry={nodes.Cube012_33.geometry}
          material={materials["material_0.019"]}
        />
        <mesh
          geometry={nodes.Cube012_34.geometry}
          material={materials["material_0.020"]}
        />
        <mesh
          geometry={nodes.Cube012_35.geometry}
          material={materials["material_0.021"]}
        />
        <mesh
          geometry={nodes.Cube012_36.geometry}
          material={materials["material_0.022"]}
        />
        <mesh
          geometry={nodes.Cube012_37.geometry}
          material={materials["material_0.023"]}
        />
        <mesh
          geometry={nodes.Cube012_38.geometry}
          material={materials["material_0.024"]}
        />
        <mesh
          geometry={nodes.Cube012_39.geometry}
          material={materials["material_0.025"]}
        />
        <mesh
          geometry={nodes.Cube012_40.geometry}
          material={materials["material_0.026"]}
        />
        <mesh
          geometry={nodes.Cube012_41.geometry}
          material={materials["material_0.028"]}
        />
        <mesh
          geometry={nodes.Cube012_42.geometry}
          material={materials["material_0.029"]}
        />
        <mesh
          geometry={nodes.Cube012_43.geometry}
          material={materials["material_0.030"]}
        />
        <mesh
          geometry={nodes.Cube012_44.geometry}
          material={materials["material_0.032"]}
        />
        <mesh
          geometry={nodes.Cube012_45.geometry}
          material={materials["Screen.002"]}
        />
        <mesh
          geometry={nodes.Cube012_46.geometry}
          material={materials["Monitor.002"]}
        />
        <mesh
          geometry={nodes.Cube012_47.geometry}
          material={materials["Tower.002"]}
        />
        <mesh
          geometry={nodes.Cube012_48.geometry}
          material={materials["Mouse.002"]}
        />
        <mesh
          geometry={nodes.Cube012_49.geometry}
          material={materials["Keyboard.002"]}
        />
        <mesh
          geometry={nodes.Cube012_50.geometry}
          material={materials.CrimeTape_Distressed_shader}
        />
        <mesh
          geometry={nodes.Cube012_51.geometry}
          material={materials["Mouse.001"]}
        />
        <mesh
          geometry={nodes.Cube012_52.geometry}
          material={materials.Wardrobe_Mat}
        />
        <mesh geometry={nodes.Cube012_53.geometry} material={materials.doors} />
        <mesh
          geometry={nodes.Cube012_54.geometry}
          material={materials.handle}
        />
        <mesh
          geometry={nodes.Cube012_55.geometry}
          material={materials["Scene_-_Root"]}
        />
        <mesh
          geometry={nodes.Cube012_56.geometry}
          material={materials.lambert3}
        />
        <mesh
          geometry={nodes.Cube012_57.geometry}
          material={materials.blinn2SG}
        />
        <mesh
          geometry={nodes.Cube012_58.geometry}
          material={materials.Monitor}
        />
        <mesh
          geometry={nodes.Cube012_59.geometry}
          material={materials["Monitor.004"]}
        />
        <mesh geometry={nodes.Cube012_60.geometry} material={materials.foot} />
        <mesh
          geometry={nodes.Cube012_61.geometry}
          material={materials.base_mano_izquierda__0}
        />
        <mesh
          geometry={nodes.Cube012_62.geometry}
          material={materials.Material}
        />
        <mesh geometry={nodes.Cube012_63.geometry} material={materials.d_mat} />
        <mesh
          geometry={nodes.Cube012_64.geometry}
          material={materials["Scene_-_Root.003"]}
        />
        <mesh
          geometry={nodes.Cube012_65.geometry}
          material={materials.blinn1SG}
        />
        <mesh
          geometry={nodes.Cube012_66.geometry}
          material={materials.Lantern}
        />
        <mesh
          geometry={nodes.Cube012_67.geometry}
          material={materials["Body.001"]}
        />
        <mesh
          geometry={nodes.Cube012_68.geometry}
          material={materials["Screen.003"]}
        />
        <mesh
          geometry={nodes.Cube012_69.geometry}
          material={materials["Button.001"]}
        />
        <mesh
          geometry={nodes.Cube012_70.geometry}
          material={materials["Pile.001"]}
        />
        <mesh geometry={nodes.Cube012_71.geometry} material={materials.iPad} />
        <mesh
          geometry={nodes.Cube012_72.geometry}
          material={materials["lambert1.004"]}
        />
        <mesh
          geometry={nodes.Cube012_73.geometry}
          material={materials.Checker}
        />
        <mesh
          geometry={nodes.Cube012_74.geometry}
          material={materials["Monitor.003"]}
        />
        <mesh
          geometry={nodes.Cube012_75.geometry}
          material={materials["Monitor.005"]}
        />
        <mesh
          geometry={nodes.Cube012_76.geometry}
          material={materials["Monitor.006"]}
        />
        <mesh
          geometry={nodes.Cube012_77.geometry}
          material={materials["Monitor.007"]}
        />
        <mesh
          geometry={nodes.Cube012_78.geometry}
          material={materials["Monitor.008"]}
        />
        <mesh
          geometry={nodes.Cube012_79.geometry}
          material={materials["Monitor.009"]}
        />
        <mesh
          geometry={nodes.Cube012_80.geometry}
          material={materials["Monitor.010"]}
        />
        <mesh
          geometry={nodes.Cube012_81.geometry}
          material={materials["Monitor.011"]}
        />
        <mesh
          geometry={nodes.Cube012_82.geometry}
          material={materials["Monitor.012"]}
        />
        <mesh
          geometry={nodes.Cube012_83.geometry}
          material={materials["Monitor.013"]}
        />
        <mesh
          geometry={nodes.Cube012_84.geometry}
          material={materials["Monitor.014"]}
        />
      </group>
    </group>
  );
}

useGLTF.preload("./models/room-comp-v3.glb");

export default Room;
