/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 public/models/room.glb 
*/
/* eslint-disable no-unused-vars */
/* eslint-disable react/no-unknown-property */
import React, { useRef, useEffect, useState } from "react";
import { useThree } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { gsap } from "gsap";

export function Room(props) {
  const { nodes, materials } = useGLTF("./models/room.glb");
  const { gl, scene, camera } = useThree();
  const map = useRef(null);
  const [animate, setAnimate] = useState(false);
  const mouseX = useRef(0);
  const mouseY = useRef(0);

  // useEffect(() => {
  //   const onMouseMove = (event) => {
  //     mouseX.current = (event.clientX / window.innerWidth) * 2 - 1;
  //     mouseY.current = (event.clientY / window.innerHeight) * 2 - 1;
  //     setAnimate(true);
  //   };

  //   const update = () => {
  //     if (animate) {
  //       const mouvementCoefficient = 0.5;

  //       gsap.to(map.current.position, {
  //         duration: 1,
  //         x: -mouseX.current * mouvementCoefficient + 3,
  //         y: mouseY.current * mouvementCoefficient - 6.5,
  //         ease: "power3.out",
  //       });
  //       setAnimate(false);
  //     }

  //     gl.render(scene, camera);
  //     requestAnimationFrame(update);
  //   };

  //   window.addEventListener("mousemove", onMouseMove, false);
  //   update();

  //   return () => {
  //     window.removeEventListener("mousemove", onMouseMove, false);
  //   };
  // }, [animate, camera, gl, scene]);

  return (
    <group {...props} dispose={null} ref={map}>
      <group
        position={[0.808, 5.692, 6.097]}
        rotation={[-Math.PI / 2, 0, 1.16]}
        scale={0.002}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.base_mano_derecha__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[57.4, -237.719, 1.789]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.base_mano_izquierda__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[-56.989, -237.719, 1.789]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.cabeza_Material_0.geometry}
            material={materials.Material}
            position={[-0.757, -23.757, 22.173]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.clavicula_derecha__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[0.279, -68.732, 22.497]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.clavicula_izquierda__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[0.279, -68.732, 22.497]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.columna_baja__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[0.279, -214.831, 22.497]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.costillas__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[0.26, -151.553, 22.334]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.cuello__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[0.279, -68.081, 22.497]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.dedos_mano_derecha__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[60.188, -268.528, 2.337]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.dedos_mano_izquierda__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[-58.991, -268.535, 2.317]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.dedos_pie_derecha__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[43.825, -476.174, -56.301]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.dedos_pie_izquierda__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[-44.177, -476.174, -56.301]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.espinilla_derecha__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[42.637, -353.033, -14.168]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.espinilla_izquierda__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[-43.043, -353.033, -14.643]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.femur_derecha__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[19.405, -248.048, -1.164]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.femur_izquierdo__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[-19.615, -248.048, -1.995]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.humero_derecha__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[57.151, -71.199, 2.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.humero_izquierdo__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[-57.799, -71.199, 2.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.pelvis__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[0.961, -210.056, 19.872]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.puanta_dedos_manos_izquierda__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[-57.567, -278.982, 1.638]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.punta_dedos_derecha__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[57.914, -278.983, 1.623]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.radio_derecha__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[57.151, -152.609, 2.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.radio_izquierda__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[-57.799, -151.907, 2.19]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.talon_derecha__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[43.825, -476.174, -15.97]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
          <mesh
            geometry={nodes.talon_izquierda__0.geometry}
            material={materials.base_mano_izquierda__0}
            position={[-44.177, -476.174, -15.97]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group
        position={[3.295, 5.447, 5.489]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.6}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <group position={[0, 0, 0.001]}>
            <group
              position={[1.372, 10, 1.935]}
              rotation={[-Math.PI / 2, 0, Math.PI / 2]}
            >
              <mesh
                geometry={nodes.door017_d_mat_0.geometry}
                material={materials.d_mat}
                position={[-636.678, 733.38, -1157.47]}
                scale={1.341}
              />
            </group>
          </group>
        </group>
      </group>
      <group
        position={[3.798, 5.305, 2.589]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.671}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.001}>
          <group position={[0, 0, 0]}>
            <group
              position={[-0.646, 10, 3.322]}
              rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
            >
              <mesh
                geometry={nodes.door016_d_mat_0.geometry}
                material={materials["d_mat.001"]}
                position={[4943.684, 2079.507, -834.464]}
                scale={1.206}
              />
            </group>
          </group>
        </group>
      </group>
      <group
        position={[-0.252, 4.707, 10.679]}
        rotation={[-Math.PI / 2, 0, 0.364]}
        scale={0.863}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={1.166}>
            <mesh
              geometry={nodes.Cube__0.geometry}
              material={materials["Scene_-_Root.003"]}
              position={[-1.711, 21.804, 0]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-4.664, 5.386, 4.532]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.058}
      >
        <mesh
          geometry={nodes.Object_2036.geometry}
          material={materials.blinn1SG}
          position={[0, 0, -0.116]}
        />
      </group>
      <group
        position={[-0.914, 6.182, 4.716]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.001}
      >
        <group scale={100}>
          <mesh
            geometry={nodes.Lantern_Lantern_0.geometry}
            material={materials.Lantern}
            position={[-7.547, -3.345, -6.219]}
            scale={0.453}
          />
        </group>
      </group>
      <group
        position={[-0.649, 5.417, 10.549]}
        rotation={[0.019, 0.849, 3.099]}
        scale={0.042}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.Object_7001.geometry}
            material={materials["Button.001"]}
            position={[-0.233, 0.663, 0.372]}
          />
          <mesh
            geometry={nodes.Object_9.geometry}
            material={materials["Pile.001"]}
            position={[-0.101, -1.024, -0.333]}
          />
          <mesh
            geometry={nodes.Object_4001.geometry}
            material={materials["Body.001"]}
          />
          <mesh
            geometry={nodes.Object_5001.geometry}
            material={materials["Screen.003"]}
          />
        </group>
      </group>
      <group position={[-4.382, 5.379, 5.196]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh
              geometry={nodes.iPad_iPad_0.geometry}
              material={materials.iPad}
              position={[-0.773, -0.506, 0]}
              rotation={[0, 0, 0.325]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-3.878, 4.259, 11.517]}
        rotation={[-Math.PI / 2, 0, -Math.PI]}
        scale={0.016}
      >
        <group rotation={[Math.PI / 2, 0, 0]}>
          <mesh
            geometry={nodes.defaultMaterial003.geometry}
            material={materials["lambert1.004"]}
            position={[-181.746, 0, 0]}
          />
          <mesh
            geometry={nodes.defaultMaterial001.geometry}
            material={materials["lambert1.004"]}
            position={[0, -0.126, -0.005]}
          />
          <mesh
            geometry={nodes.defaultMaterial002.geometry}
            material={materials["lambert1.004"]}
            position={[0, -0.126, 0.076]}
          />
        </group>
      </group>
      <mesh
        geometry={nodes.Object_2035.geometry}
        material={materials.foot}
        position={[-4.258, 7.154, 8.556]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.008}
      />
      <group
        position={[-1.152, 5.379, 3.81]}
        rotation={[-Math.PI / 2, 0, 2.941]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Monitor_Low_Monitor_0.geometry}
            material={materials.Monitor}
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group
        position={[-1.149, 5.379, 5.096]}
        rotation={[-Math.PI / 2, 0, -2.973]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Monitor_Low_Monitor_0001.geometry}
            material={materials["Monitor.003"]}
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group
        position={[-1.02, 5.379, 7.475]}
        rotation={[-Math.PI / 2, 0, 2.779]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Monitor_Low_Monitor_0002.geometry}
            material={materials["Monitor.004"]}
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group position={[-1.953, 5.379, 3.58]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Monitor_Low_Monitor_0003.geometry}
              material={materials["Monitor.005"]}
              position={[0.223, -0.098, 0]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-1.733, 5.379, 4.842]}
        rotation={[-Math.PI / 2, 0, 0.655]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Monitor_Low_Monitor_0004.geometry}
            material={materials["Monitor.006"]}
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group position={[-1.702, 5.379, 8.81]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Monitor_Low_Monitor_0005.geometry}
              material={materials["Monitor.007"]}
              position={[0, -0.031, 0]}
            />
          </group>
        </group>
      </group>
      <group position={[-1.604, 5.379, 7.517]} rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Monitor_Low_Monitor_0006.geometry}
            material={materials["Monitor.008"]}
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group
        position={[-4.89, 5.379, 3.488]}
        rotation={[-Math.PI / 2, 0, 0.391]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Monitor_Low_Monitor_0007.geometry}
            material={materials["Monitor.009"]}
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group
        position={[-4.898, 5.379, 7.413]}
        rotation={[-Math.PI / 2, 0, -0.473]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Monitor_Low_Monitor_0008.geometry}
            material={materials["Monitor.010"]}
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group
        position={[-4.837, 5.379, 9.032]}
        rotation={[-Math.PI / 2, 0, 0.414]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Monitor_Low_Monitor_0009.geometry}
            material={materials["Monitor.011"]}
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group
        position={[-4.255, 5.379, 3.694]}
        rotation={[-Math.PI / 2, 0, -2.583]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Monitor_Low_Monitor_0010.geometry}
            material={materials["Monitor.012"]}
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group
        position={[-4.353, 5.379, 7.59]}
        rotation={[-Math.PI / 2, 0, -2.573]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          >
            <mesh
              geometry={nodes.Monitor_Low_Monitor_0011.geometry}
              material={materials["Monitor.013"]}
              position={[-0.058, 0.249, 0]}
            />
          </group>
        </group>
      </group>
      <group
        position={[-4.459, 5.379, 5.099]}
        rotation={[-Math.PI / 2, 0, 1.896]}
      >
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <mesh
            geometry={nodes.Monitor_Low_Monitor_0012.geometry}
            material={materials["Monitor.014"]}
            position={[-0.922, 25.347, -0.032]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={100}
          />
        </group>
      </group>
      <group position={[-2.759, 4.612, 6.533]} scale={[3.953, 0.137, 5.172]}>
        <mesh geometry={nodes.Cube002.geometry} material={materials.Murs} />
        <mesh
          geometry={nodes.Cube002_1.geometry}
          material={materials["Material.002"]}
        />
        <mesh geometry={nodes.Cube002_2.geometry} material={materials.Sol} />
        <mesh
          geometry={nodes.Cube002_3.geometry}
          material={materials["Mur Vegetal"]}
        />
      </group>
      <mesh
        geometry={nodes.low_poly_table_lambert3_0001.geometry}
        material={materials["lambert3.001"]}
        position={[-5.089, 4.84, 3.983]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0002.geometry}
        material={materials["lambert3.002"]}
        position={[-4.155, 4.84, 3.978]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0003.geometry}
        material={materials["lambert3.003"]}
        position={[-4.165, 4.84, 2.523]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0004.geometry}
        material={materials["lambert3.004"]}
        position={[-4.151, 4.84, 6.308]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0005.geometry}
        material={materials["lambert3.005"]}
        position={[-4.141, 4.84, 7.762]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0006.geometry}
        material={materials["lambert3.006"]}
        position={[-5.075, 4.84, 7.767]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0007.geometry}
        material={materials["lambert3.007"]}
        position={[-5.085, 4.84, 6.313]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0008.geometry}
        material={materials["lambert3.008"]}
        position={[-1.942, 4.84, 6.271]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0009.geometry}
        material={materials["lambert3.009"]}
        position={[-1.932, 4.84, 7.725]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0010.geometry}
        material={materials["lambert3.010"]}
        position={[-0.998, 4.84, 7.72]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0011.geometry}
        material={materials["lambert3.011"]}
        position={[-1.008, 4.84, 6.266]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0012.geometry}
        material={materials["lambert3.012"]}
        position={[-1.022, 4.84, 2.481]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0013.geometry}
        material={materials["lambert3.013"]}
        position={[-1.012, 4.84, 3.935]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0014.geometry}
        material={materials["lambert3.014"]}
        position={[-1.946, 4.84, 3.94]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0015.geometry}
        material={materials["lambert3.015"]}
        position={[-1.956, 4.84, 2.486]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.Object_3001.geometry}
        material={materials["material_0.001"]}
        position={[-0.461, 5.652, 4.313]}
        rotation={[Math.PI, 0.199, 0]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3002.geometry}
        material={materials["material_0.002"]}
        position={[-0.306, 5.652, 5.803]}
        rotation={[Math.PI, -0.135, 0]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3003.geometry}
        material={materials["material_0.003"]}
        position={[0.15, 5.652, 5.072]}
        rotation={[Math.PI, -0.064, 0]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3006.geometry}
        material={materials["material_0.006"]}
        position={[-2.959, 5.652, 4.639]}
        rotation={[0, 0.43, Math.PI]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3007.geometry}
        material={materials["material_0.007"]}
        position={[-2.459, 5.652, 5.271]}
        rotation={[0, -0.001, -Math.PI]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3009.geometry}
        material={materials["material_0.009"]}
        position={[-5.839, 5.652, 4.708]}
        rotation={[0, -0.157, -Math.PI]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3010.geometry}
        material={materials["material_0.010"]}
        position={[-6.32, 5.145, 3.947]}
        rotation={[-0.003, 1.308, -1.568]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3013.geometry}
        material={materials["material_0.013"]}
        position={[-1.749, 4.881, 5.556]}
        rotation={[-2.037, -1.562, -2.055]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3014.geometry}
        material={materials["material_0.014"]}
        position={[-3.29, 5.652, 4.421]}
        rotation={[Math.PI, 0.08, 0]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3015.geometry}
        material={materials["material_0.015"]}
        position={[-3.556, 5.652, 3.983]}
        rotation={[Math.PI, -0.132, 0]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3016.geometry}
        material={materials["material_0.016"]}
        position={[-3.716, 5.652, 7.662]}
        rotation={[Math.PI, -0.088, 0]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3017.geometry}
        material={materials["material_0.017"]}
        position={[-3.716, 5.652, 8.275]}
        rotation={[Math.PI, 0.091, 0]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3018.geometry}
        material={materials["material_0.018"]}
        position={[-4.777, 5.681, 10.029]}
        rotation={[Math.PI, 1.087, 0]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3019.geometry}
        material={materials["material_0.019"]}
        position={[-3.741, 5.652, 9.637]}
        rotation={[Math.PI, -0.109, 0]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3020.geometry}
        material={materials["material_0.020"]}
        position={[-5.796, 5.652, 7.665]}
        rotation={[0, 0.129, Math.PI]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3021.geometry}
        material={materials["material_0.021"]}
        position={[-5.631, 5.772, 6.977]}
        rotation={[0, -0.186, -Math.PI]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3022.geometry}
        material={materials["material_0.022"]}
        position={[-6.163, 4.409, 8.732]}
        rotation={[-3.078, 0.978, -2.389]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3023.geometry}
        material={materials["material_0.023"]}
        position={[-5.873, 5.668, 9.18]}
        rotation={[0, 0.219, Math.PI]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3024.geometry}
        material={materials["material_0.024"]}
        position={[-2.459, 5.652, 9.069]}
        rotation={[0, 0.143, Math.PI]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3025.geometry}
        material={materials["material_0.025"]}
        position={[-2.278, 5.652, 8.437]}
        rotation={[0, -0.122, -Math.PI]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3026.geometry}
        material={materials["material_0.026"]}
        position={[-2.293, 5.652, 6.797]}
        rotation={[0, -0.245, -Math.PI]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3028.geometry}
        material={materials["material_0.028"]}
        position={[-0.27, 5.652, 8.969]}
        rotation={[Math.PI, -0.042, 0]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3029.geometry}
        material={materials["material_0.029"]}
        position={[-1.105, 5.093, 9.038]}
        rotation={[3.122, -0.362, -2.173]}
        scale={0.047}
      />
      <mesh
        geometry={nodes.Object_3030.geometry}
        material={materials["material_0.030"]}
        position={[-0.461, 5.652, 8.111]}
        rotation={[Math.PI, 0.166, 0]}
        scale={0.047}
      />
      <group
        position={[3.255, 7.737, 3.663]}
        rotation={[-Math.PI / 2, 0, 1.572]}
        scale={[0.229, 1.909, 0.409]}
      >
        <mesh
          geometry={nodes.SM_overhead_light_T_overhead_light_0005.geometry}
          material={materials["T_overhead_light.005"]}
        />
        <mesh
          geometry={nodes.SM_overhead_light_T_overhead_light_0005_1.geometry}
          material={materials["T_overhead_light.003"]}
        />
        <mesh
          geometry={nodes.SM_overhead_light_T_overhead_light_0005_2.geometry}
          material={materials["T_overhead_light.004"]}
        />
        <mesh
          geometry={nodes.SM_overhead_light_T_overhead_light_0005_3.geometry}
          material={materials.T_overhead_light}
        />
      </group>
      <mesh
        geometry={nodes.Cube012.geometry}
        material={materials["Material.005"]}
        position={[-2.762, 7.81, 6.554]}
        scale={[3.935, 0.078, 5.155]}
      />
      <mesh
        geometry={nodes.Cylinder.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder001.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder002.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder003.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder004.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder005.geometry}
        material={materials.projector}
        position={[-4.259, 12.406, 19.721]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder006.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder007.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder008.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder009.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder010.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder011.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder012.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder013.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder014.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder015.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder016.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder017.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder018.geometry}
        material={materials.projector}
        position={[-4.259, 12.406, 19.721]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder019.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder020.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder021.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder022.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Cylinder023.geometry}
        material={materials.projector}
        position={[-4.259, 7.603, 8.579]}
        scale={[0.017, 0.152, 0.017]}
      />
      <mesh
        geometry={nodes.Object_3033.geometry}
        material={materials["material_0.032"]}
        position={[-0.436, 5.652, 10.863]}
        rotation={[Math.PI, 1.115, 0]}
        scale={0.047}
      />
      <group
        position={[0.209, 5.417, 10.353]}
        rotation={[-Math.PI / 2, 0, -0.444]}
        scale={0.159}
      >
        <mesh
          geometry={nodes.Cube003_Screen_0002.geometry}
          material={materials["Screen.002"]}
        />
        <mesh
          geometry={nodes.Cube003_Screen_0002_1.geometry}
          material={materials["Monitor.002"]}
        />
        <mesh
          geometry={nodes.Cube003_Screen_0002_2.geometry}
          material={materials["Tower.002"]}
        />
      </group>
      <mesh
        geometry={nodes.Cube003_Mouse_0001.geometry}
        material={materials["Mouse.002"]}
        position={[0.226, 5.417, 10.335]}
        rotation={[-Math.PI / 2, 0, 0.069]}
        scale={0.159}
      />
      <mesh
        geometry={nodes.Cube003_Keyboard_0001.geometry}
        material={materials["Keyboard.002"]}
        position={[0.099, 5.417, 10.412]}
        rotation={[-Math.PI / 2, 0, -0.688]}
        scale={0.159}
      />
      <mesh
        geometry={nodes.Cube019.geometry}
        material={materials.panneau}
        position={[0.834, 5.915, 6.777]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.089, 0.288, 0.978]}
      />
      <mesh
        geometry={nodes.Cube017.geometry}
        material={materials["Material.001"]}
        position={[0.947, 6.238, 8.715]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.089, 0.288, 0.978]}
      />
      <mesh
        geometry={nodes.Cube015.geometry}
        material={materials["Material.003"]}
        position={[0.843, 6.537, 10.81]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={[0.089, 0.288, 0.978]}
      />
      <mesh
        geometry={nodes.Cube016.geometry}
        material={materials["Material.004"]}
        position={[-6.416, 6.68, 9.08]}
        scale={[0.089, 0.288, 0.978]}
      />
      <mesh
        geometry={nodes.Body1_CrimeTape_Distressed_shader_0.geometry}
        material={materials.CrimeTape_Distressed_shader}
        position={[-0.558, 4.76, 11.002]}
        rotation={[0, -0.575, 0]}
        scale={0.007}
      />
      <mesh
        geometry={nodes.Body2_CrimeTape_Distressed_shader_0.geometry}
        material={materials.CrimeTape_Distressed_shader}
        position={[2.875, 4.76, 3.845]}
        rotation={[0, 1.227, 0]}
        scale={0.007}
      />
      <mesh
        geometry={nodes.CrimeTapeMedium_CrimeTape_Distressed_shader_0.geometry}
        material={materials.CrimeTape_Distressed_shader}
        position={[-4.556, 4.789, 6.781]}
        scale={0.007}
      />
      <mesh
        geometry={nodes.CrimeTapeSmall_CrimeTape_Distressed_shader_0.geometry}
        material={materials.CrimeTape_Distressed_shader}
        position={[-2.64, 4.71, 9.71]}
        scale={[0.008, 0.007, 0.007]}
      />
      <mesh
        geometry={nodes.Cube003_Mouse_0.geometry}
        material={materials["Mouse.001"]}
        position={[-1.872, 5.381, 5.154]}
        rotation={[-Math.PI / 2, 0, -1.342]}
        scale={0.159}
      />
      <mesh
        geometry={nodes.defaultMaterial004.geometry}
        material={materials.Wardrobe_Mat}
        position={[-6.341, 5.536, 10.746]}
        rotation={[-Math.PI / 2, 0, -3.125]}
        scale={0.247}
      />
      <mesh
        geometry={nodes.defaultMaterial005.geometry}
        material={materials.Wardrobe_Mat}
        position={[-6.287, 4.925, 10.745]}
        rotation={[-Math.PI / 2, 0, -3.125]}
        scale={0.247}
      />
      <mesh
        geometry={nodes.defaultMaterial006.geometry}
        material={materials.Wardrobe_Mat}
        position={[-6.214, 5.692, 10.46]}
        rotation={[-Math.PI / 2, 0, -3.125]}
        scale={0.247}
      />
      <mesh
        geometry={nodes.defaultMaterial007.geometry}
        material={materials.Wardrobe_Mat}
        position={[-6.169, 5.628, 10.66]}
        rotation={[-Math.PI / 2, 0, -3.125]}
        scale={0.247}
      />
      <mesh
        geometry={nodes.defaultMaterial008.geometry}
        material={materials.Wardrobe_Mat}
        position={[-6.205, 5.692, 11.028]}
        rotation={[-Math.PI / 2, 0, -3.125]}
        scale={0.247}
      />
      <mesh
        geometry={nodes.defaultMaterial009.geometry}
        material={materials.Wardrobe_Mat}
        position={[-6.166, 5.628, 10.827]}
        rotation={[-Math.PI / 2, 0, -3.125]}
        scale={0.247}
      />
      <mesh
        geometry={nodes.door_window_0.geometry}
        material={materials.window}
        position={[-0.603, 5.725, 1.527]}
        rotation={[-Math.PI / 2, 0, 0.001]}
        scale={[0.498, 0.021, 0.249]}
      />
      <mesh
        geometry={nodes.Low___0.geometry}
        material={materials["Scene_-_Root"]}
        position={[1.618, 4.989, 5.644]}
        rotation={[-Math.PI / 2, 0, -1.57]}
        scale={0.201}
      />
      <mesh
        geometry={nodes.low_poly_table_lambert3_0.geometry}
        material={materials.lambert3}
        position={[-5.099, 4.84, 2.528]}
        rotation={[0, -1.563, 0]}
        scale={[0.003, 0.004, 0.005]}
      />
      <mesh
        geometry={nodes.Object_2032.geometry}
        material={materials.anisotropic2SG}
        position={[-2.402, 5.282, 1.045]}
        rotation={[-Math.PI / 2, 0, 3.117]}
        scale={0.11}
      />
      <mesh
        geometry={nodes.Object_2034.geometry}
        material={materials.blinn2SG}
        position={[-4.213, 5.378, 8.358]}
        rotation={[-Math.PI / 2, 0, 0]}
        scale={0.076}
      />
      <mesh
        geometry={nodes.Object_3032.geometry}
        material={materials.blinn4SG}
        position={[-0.675, 4.744, 2.503]}
        rotation={[-Math.PI / 2, 0, -3.138]}
        scale={[0.15, 0.11, 0.098]}
      />
      <mesh
        geometry={nodes.Cube018.geometry}
        material={nodes.Cube018.material}
        position={[2.777, 4.602, 7.619]}
        scale={[1.58, 0.084, 1.616]}
      />
    </group>
  );
}

useGLTF.preload("./models/room.glb");

export default Room;
